import React, { useEffect, useState } from "react";
import { useGameContext } from "../context/GameContext";

const sports = [
  "Soccer",
  "Basketball",
  "Tennis",
  "Cricket",
  "Baseball",
  "Swimming",
  "Volleyball",
  "Rugby",
  "Badminton",
  "Hockey",
  "Golf",
  "Table Tennis",
  "Squash",
  "Handball",
  "Boxing",
  "Wrestling",
  "Martial Arts",
  "Cycling",
  "Skateboarding",
  "Snowboarding",
  "Skiing",
  "Surfing",
  "Archery",
  "Fencing",
  "Lacrosse",
  "Bowling",
  "Diving",
  "Gymnastics",
  "Rowing",
  "Kayaking",
  "Horse Racing",
  "Motorsport",
  "Sailing",
  "Water Polo",
  "Triathlon",
  "Track and Field",
  "Weightlifting",
  "Judo",
  "Karate",
  "Taekwondo",
  "CrossFit",
  "Cheerleading",
  "Curling",
  "Snooker",
  "Chess",
  "Esports",
  "Roller Derby",
  "Ultimate Frisbee",
  "Paintball",
  "BMX",
  "Parkour",
];
const animals = [
  "Aardvark",
  "Albatross",
  "Alligator",
  "Alpaca",
  "Ant",
  "Anteater",
  "Antelope",
  "Ape",
  "Armadillo",
  "Donkey",
  "Baboon",
  "Badger",
  "Barracuda",
  "Bat",
  "Bear",
  "Beaver",
  "Bee",
  "Bison",
  "Boar",
  "Buffalo",
  "Butterfly",
  "Camel",
  "Capybara",
  "Caribou",
  "Cassowary",
  "Cat",
  "Caterpillar",
  "Cattle",
  "Chamois",
  "Cheetah",
  "Chicken",
  "Chimpanzee",
  "Chinchilla",
  "Clam",
  "Cobra",
  "Cockroach",
  "Cod",
  "Cormorant",
  "Coyote",
  "Crab",
  "Crane",
  "Crocodile",
  "Crow",
  "Deer",
  "Dinosaur",
  "Dog",
  "Dogfish",
  "Dolphin",
  "Donkey",
  "Dotterel",
  "Dove",
  "Dragonfly",
  "Duck",
  "Dugong",
  "Dunlin",
  "Eagle",
  "Echidna",
  "Eel",
  "Elephant",
  "Elk",
  "Emu",
  "Falcon",
  "Ferret",
  "Finch",
  "Fish",
  "Flamingo",
  "Fly",
  "Fox",
  "Frog",
  "Gaur",
  "Gazelle",
  "Gerbil",
  "Giraffe",
  "Gnat",
  "Gnu",
  "Goat",
  "Goldfinch",
  "Goldfish",
  "Goose",
  "Gorilla",
  "Goshawk",
  "Grasshopper",
  "Grouse",
  "Guan",
  "Gull",
  "Hamster",
  "Hare",
  "Hawk",
  "Hedgehog",
  "Heron",
  "Herring",
  "Hippopotamus",
  "Hornet",
  "Horse",
  "Human",
  "Hummingbird",
  "Hyena",
  "Ibex",
  "Ibis",
  "Jackal",
  "Jaguar",
  "Jay",
  "Jellyfish",
  "Kangaroo",
  "Kingfisher",
  "Koala",
  "Kookabura",
  "Kouprey",
  "Kudu",
  "Lapwing",
  "Lark",
  "Lemur",
  "Leopard",
  "Lion",
  "Llama",
  "Lobster",
  "Locust",
  "Loris",
  "Louse",
  "Lyrebird",
  "Magpie",
  "Mallard",
  "Manatee",
  "Mandrill",
  "Mantis",
  "Marten",
  "Meerkat",
  "Mink",
  "Mole",
  "Mongoose",
  "Monkey",
  "Moose",
  "Mosquito",
  "Mouse",
  "Mule",
  "Narwhal",
  "Newt",
  "Nightingale",
  "Octopus",
  "Okapi",
  "Opossum",
  "Oryx",
  "Ostrich",
  "Otter",
  "Owl",
  "Ox",
  "Oyster",
  "Panther",
  "Parrot",
  "Partridge",
  "Peafowl",
  "Pelican",
  "Penguin",
  "Pheasant",
  "Pig",
  "Pigeon",
  "Pony",
  "Porcupine",
  "Porpoise",
  "Quail",
  "Quelea",
  "Quetzal",
  "Rabbit",
  "Raccoon",
  "Rail",
  "Ram",
  "Rat",
  "Raven",
  "Red deer",
  "Red panda",
  "Reindeer",
  "Rhinoceros",
  "Rook",
  "Salamander",
  "Salmon",
  "Sand Dollar",
  "Sandpiper",
  "Sardine",
  "Scorpion",
  "Seahorse",
  "Seal",
  "Shark",
  "Sheep",
  "Shrew",
  "Skunk",
  "Snail",
  "Snake",
  "Sparrow",
  "Spider",
  "Spoonbill",
  "Squid",
  "Squirrel",
  "Starling",
  "Stingray",
  "Stinkbug",
  "Stork",
  "Swallow",
  "Swan",
  "Tapir",
  "Tarsier",
  "Termite",
  "Tiger",
  "Toad",
  "Trout",
  "Turkey",
  "Turtle",
  "Vicuña",
  "Viper",
  "Vulture",
  "Wallaby",
  "Walrus",
  "Wasp",
  "Weasel",
  "Whale",
  "Wildcat",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Woodcock",
  "Woodpecker",
  "Worm",
  "Wren",
  "Yak",
  "Zebra",
];
const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. 'Swaziland')",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
const capitals = [
  "Kabul",
  "Tirana",
  "Algiers",
  "Andorra la Vella",
  "Luanda",
  "St Johns",
  "Buenos Aires",
  "Yerevan",
  "Canberra",
  "Vienna",
  "Baku",
  "Nassau",
  "Manama",
  "Dhaka",
  "Bridgetown",
  "Minsk",
  "Brussels",
  "Belmopan",
  "Porto Novo",
  "Thimphu",
  "Sucre",
  "Sarajevo",
  "Gaborone",
  "Brasilia",
  "Bandar Seri Begawan",
  "Sofia",
  "Ouagadougou",
  "Gitega",
  "Praia",
  "Phnom Penh",
  "Yaounde",
  "Ottawa",
  "Bangui",
  "N Djamena",
  "Santiago",
  "Beijing",
  "Bogota",
  "Moroni",
  "Brazzaville",
  "San Jose",
  "Zagreb",
  "Havana",
  "Nicosia",
  "Prague",
  "Kinshasa",
  "Copenhagen",
  "Djibouti",
  "Roseau",
  "Santo Domingo",
  "Quito",
  "Cairo",
  "San Salvador",
  "Malabo",
  "Asmara",
  "Tallinn",
  "Mbabane",
  "Addis Ababa",
  "Suva",
  "Helsinki",
  "Paris",
  "Libreville",
  "Banjul",
  "Tbilisi",
  "Berlin",
  "Accra",
  "Athens",
  "St Georges",
  "Guatemala City",
  "Conakry",
  "Bissau",
  "Georgetown",
  "Port au Prince",
  "Port au Prince",
  "Vatican City",
  "Tegucigalpa",
  "Budapest",
  "Reykjavik",
  "New Delhi",
  "Jakarta",
  "Tehran",
  "Baghdad",
  "Dublin",
  "Jerusalem",
  "Rome",
  "Kingston",
  "Tokyo",
  "Amman",
  "Nur Sultan",
  "Nairobi",
  "Tarawa Atoll",
  "Kuwait City",
  "Bishkek",
  "Vientiane",
  "Riga",
  "Beirut",
  "Maseru",
  "Monrovia",
  "Tripoli",
  "Vaduz",
  "Vilnius",
  "Luxembourg",
  "Antananarivo",
  "Lilongwe",
  "Kuala Lumpur",
  "Male",
  "Bamako",
  "Valletta",
  "Majuro",
  "Nouakchott",
  "Port Louis",
  "Mexico City",
  "Palikir",
  "Chisinau",
  "Monaco",
  "Ulaanbaatar",
  "Podgorica",
  "Rabat",
  "Maputo",
  "Naypyidaw",
  "Windhoek",
  "Yaren District",
  "Kathmandu",
  "Amsterdam",
  "Wellington",
  "Managua",
  "Niamey",
  "Abuja",
  "Pyongyang",
  "Skopje",
  "Oslo",
  "Muscat",
  "Islamabad",
  "Ngerulmud",
  "Ramallah",
  "Panama City",
  "Port Moresby",
  "Asuncion",
  "Lima",
  "Manila",
  "Warsaw",
  "Lisbon",
  "Doha",
  "Bucharest",
  "Moscow",
  "Kigali",
  "Basseterre",
  "Castries",
  "Kingstown",
  "Apia",
  "San Marino",
  "Sao Tome",
  "Riyadh",
  "Dakar",
  "Belgrade",
  "Victoria",
  "Freetown",
  "Singapore",
  "Bratislava",
  "Ljubljana",
  "Honiara",
  "Mogadishu",
  "Pretoria",
  "Seoul",
  "Juba",
  "Madrid",
  "Colombo",
  "Khartoum",
  "Paramaribo",
  "Stockholm",
  "Bern",
  "Damascus",
  "Dushanbe",
  "Dodoma",
  "Bangkok",
  "Dili",
  "Lome",
  "Nukualoha",
  "Port of Spain",
  "Tunis",
  "Ankara",
  "Ashgabat",
  "Funafuti",
  "Kampala",
  "Kyiv",
  "Abu Dhabi",
  "London",
  "Washington DC",
  "Montevideo",
  "Tashkent",
  "Port Vila",
  "Caracas",
  "Hanoi",
  "Sanaa",
  "Lusaka",
  "Harare",
];
const tvShows = [
  "Breaking Bad",
  "Game of Thrones",
  "Stranger Things",
  "The Crown",
  "Friends",
  "The Office",
  "Westworld",
  "Better Call Saul",
  "The Mandalorian",
  "The Simpsons",
  "Sherlock",
  "Black Mirror",
  "The Walking Dead",
  "House of Cards",
  "Narcos",
  "Mindhunter",
  "Lost",
  "Dexter",
  "True Detective",
  "The Witcher",
  "Fargo",
  "Peaky Blinders",
  "Vikings",
  "Suits",
  "How I Met Your Mother",
  "The Big Bang Theory",
  "Rick and Morty",
  "Grey Anatomy",
  "The Handmaids Tale",
  "Seinfeld",
  "The West Wing",
  "Chernobyl",
  "Homeland",
  "Buffy the Vampire Slayer",
  "Fringe",
  "Doctor Who",
  "Better Things",
  "The Expanse",
  "Ozark",
];

const movies = [
  "The Godfather",
  "Pulp Fiction",
  "Forrest Gump",
  "The Dark Knight",
  "Inception",
  "Fight Club",
  "The Matrix",
  "Goodfellas",
  "The Shawshank Redemption",
  "Interstellar",
  "Gladiator",
  "Titanic",
  "Jurassic Park",
  "The Lord of the Rings",
  "Star Wars",
  "Avatar",
  "The Lion King",
  "Back to the Future",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "Schindlers List",
  "Braveheart",
  "Toy Story",
  "Pirates of the Caribbean",
  "The Avengers",
  "The Departed",
  "The Prestige",
  "Casino Royale",
  "The Social Network",
  "Black Panther",
  "The Incredibles",
  "La La Land",
  "The Grand Budapest Hotel",
  "Mad Max Fury Road",
  "The Breakfast Club",
  "Eternal Sunshine of the Spotless Mind",
  "Jumanji",
  "The Revenant",
  "The Truman Show",
  "The Bourne Identity",
  "The Hobbit",
  "The Lego Movie",
  "Finding Nemo",
  "The Help",
  "Up",
  "The Martian",
  "Gravity",
  "Logan",
  "Django Unchained",
];

export default function useRandomWord() {
  const [word, setWord] = useState<string>();

  const { category } = useGameContext();

  function getRandomWord(
    category:
      | "Movies"
      | "TV Shows"
      | "Countries"
      | "Capital Cities"
      | "Animals"
      | "Sports"
  ) {
    let randomArray: string[] = [];

    switch (category) {
      case "Sports":
        randomArray = sports; // no 'let' here
        break;
      case "Animals":
        randomArray = animals;
        break;
      case "Countries":
        randomArray = countries;
        break;
      case "Capital Cities":
        randomArray = capitals;
        break;
      case "Movies":
        randomArray = movies;
        break;
      case "TV Shows":
        randomArray = tvShows;
        break;
      // add other cases
    }

    const randomIndex = Math.floor(Math.random() * randomArray.length);

    return { randomIndex };
  }

  useEffect(() => {
    if (!category) return;

    let randomArray: string[] = [];

    switch (category) {
      case "Sports":
        randomArray = sports; // no 'let' here
        break;
      case "Animals":
        randomArray = animals;
        break;
      case "Countries":
        randomArray = countries;
        break;
      case "Capital Cities":
        randomArray = capitals;
        break;
      case "Movies":
        randomArray = movies;
        break;
      case "TV Shows":
        randomArray = tvShows;
        break;
      // add other cases
    }

    const randomIndex = Math.floor(Math.random() * randomArray.length);
    setWord(randomArray[randomIndex]);
  }, [category]);

  return { word, setWord, getRandomWord };
}
