import type { Metadata } from "next";
import { Geist, Geist_Mono, Mouse_Memoirs } from "next/font/google";
import "./globals.css";

const MouseMemoirsFont = Mouse_Memoirs({
  subsets: ["latin"],
  weight: "400", // only available weight
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hangman | Andrew",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${MouseMemoirsFont.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
